; IconPointers indexes (see data/icon_pointers.asm)
	const_def
	const ICON_NULL
	const ICON_POLIWAG
	const ICON_JIGGLYPUFF
	const ICON_DIGLETT
	const ICON_PIKACHU
	const ICON_STARYU
	const ICON_FISH
	const ICON_BIRD
	const ICON_MONSTER
	const ICON_CLEFAIRY
	const ICON_ODDISH
	const ICON_BUG
	const ICON_GHOST
	const ICON_LAPRAS
	const ICON_HUMANSHAPE
	const ICON_FOX
	const ICON_EQUINE
	const ICON_SHELL
	const ICON_BLOB
	const ICON_SERPENT
	const ICON_VOLTORB
	const ICON_SQUIRTLE
	const ICON_BULBASAUR
	const ICON_CHARMANDER
	const ICON_CATERPILLAR
	const ICON_UNOWN
	const ICON_GEODUDE
	const ICON_FIGHTER
	const ICON_EGG
	const ICON_JELLYFISH
	const ICON_MOTH
	const ICON_BAT
	const ICON_SNORLAX
	const ICON_HO_OH
	const ICON_LUGIA
	const ICON_GYARADOS
	const ICON_SLOWPOKE
	const ICON_SUDOWOODO
	const ICON_BIGMON
	const ICON_BALLOONS
	const ICON_BALLOONSOWCHRIS
	const ICON_BALLOONSOWKRIS
DEF NUM_ICONS EQU const_value - 1

; LoadMenuMonIcon.Jumptable indexes (see engine/gfx/mon_icons.asm)
	const_def
	const MONICON_PARTYMENU
	const MONICON_NAMINGSCREEN
	const MONICON_MOVES
	const MONICON_TRADE
	const MONICON_MOBILE1
	const MONICON_MOBILE2
	const MONICON_UNUSED

; Type icon constants

	const_def
	const TYPEICON_GHOST
	const TYPEICON_DARK
	const TYPEICON_NORMAL
	const TYPEICON_GROUND
	const TYPEICON_FIRE
	const TYPEICON_PSYCHIC
	const TYPEICON_FIGHTING
	const TYPEICON_FLYING
	const TYPEICON_POISON
	const TYPEICON_ROCK
	const TYPEICON_GRASS
	const TYPEICON_BUG
	const TYPEICON_STEEL
	const TYPEICON_DRAGON
	const TYPEICON_WATER
	const TYPEICON_ELECTRIC
	const TYPEICON_ICE
DEF NUM_TYPE_ICONS EQU const_value - 1

; Type icon palette constants

	const_def
	const TYPEICONPAL_GHOST
	const TYPEICONPAL_DARK
	const TYPEICONPAL_NORMAL
	const TYPEICONPAL_GROUND
	const TYPEICONPAL_FIRE
	const TYPEICONPAL_PSYCHIC
	const TYPEICONPAL_FIGHTING
	const TYPEICONPAL_FLYING
	const TYPEICONPAL_POISON
	const TYPEICONPAL_ROCK
	const TYPEICONPAL_GRASS
	const TYPEICONPAL_BUG
	const TYPEICONPAL_STEEL
	const TYPEICONPAL_DRAGON
	const TYPEICONPAL_WATER
	const TYPEICONPAL_ELECTRIC
	const TYPEICONPAL_ICE
