	tilepal 0, BROWN, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, BROWN, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, PRIORITY_ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, BROWN, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, WATER, ROOF, ROOF, ROOF, ROOF, ROOF, GRAY, GRAY
	tilepal 0, WATER, WATER, ROOF, ROOF, ROOF, ROOF, WATER, WATER
	tilepal 0, BROWN, ROOF, BROWN, BROWN, BROWN, WATER, GRAY, GRAY
	tilepal 0, WATER, WATER, ROOF, ROOF, ROOF, ROOF, WATER, WATER
	tilepal 0, YELLOW, YELLOW, YELLOW, YELLOW, BROWN, GRAY, GRAY, WATER
	tilepal 0, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 0, BROWN, BROWN, GRAY, GRAY, WATER, WATER, WATER, WATER
	tilepal 0, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER

rept 32
	db $ff
endr

	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, BROWN, BROWN
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, GREEN, GREEN
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, BROWN, BROWN
	tilepal 1, ROOF, ROOF, ROOF, ROOF, GREEN, GREEN, GREEN, GREEN
