	tilepal 0, GRAY, BROWN, BROWN, RED, GREEN, GREEN, GRAY, RED
	tilepal 0, WATER, WATER, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, GREEN, WATER, GREEN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN, GREEN
	tilepal 0, BROWN, BROWN, BROWN, GREEN, GREEN, BROWN, YELLOW, WATER
	tilepal 0, WATER, GREEN, GREEN, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 0, BROWN, BROWN, WATER, WATER, BROWN, BROWN, BROWN, GREEN
	tilepal 0, GREEN, BROWN, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 0, RED, BROWN, WATER, WATER, BROWN, GREEN, BROWN, BROWN
	tilepal 0, BROWN, WATER, BROWN, BROWN, BROWN, BROWN, WATER, WATER
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, WATER, GRAY, GRAY, GREEN, BROWN, BROWN, WATER, PRIORITY_GRAY

rept 32
	db $ff
endr

	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, RED
	tilepal 1, RED, ROOF, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN, GRAY
	tilepal 1, YELLOW, YELLOW, BROWN, BROWN, BROWN, BROWN, RED, RED
	tilepal 1, BROWN, BROWN, GRAY, GREEN, TEXT, RED, RED, RED
	tilepal 1, RED, RED, GREEN, GREEN, GREEN, GREEN, WATER, WATER
	tilepal 1, BROWN, BROWN, YELLOW, TEXT, TEXT, TEXT, TEXT, TEXT
	tilepal 1, TEXT, TEXT, GREEN, GREEN, GREEN, GREEN, WATER, WATER
	tilepal 1, WATER, GRAY, TEXT, GREEN, GREEN, PRIORITY_GREEN, PRIORITY_GREEN, GREEN
	tilepal 1, BROWN, BROWN, WATER, WATER, WATER, WATER, WATER, BROWN
	tilepal 1, GREEN, GREEN, PRIORITY_GREEN, PRIORITY_GREEN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, PRIORITY_GREEN, PRIORITY_GREEN, GREEN, GREEN, BROWN, BROWN, GREEN, GREEN
