	tilepal 0, GRAY, GREEN, BROWN, RED, GREEN, BROWN, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, RED, RED, RED, GRAY, WATER, ROOF, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, BROWN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, RED, RED, RED, BROWN, BROWN, BROWN, BROWN, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GREEN, GREEN, BROWN, BROWN, GREEN
	tilepal 0, RED, RED, RED, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, GREEN, GREEN, GREEN, BROWN, BROWN, GREEN
	tilepal 0, BROWN, RED, BROWN, BROWN, GRAY, GRAY, GRAY, BROWN
	tilepal 0, BROWN, BROWN, GREEN, GREEN, GRAY, GRAY, GRAY, RED
	tilepal 0, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY, GRAY, BROWN
	tilepal 0, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, GRAY, WATER

rept 32
	db $ff
endr

	tilepal 1, WATER, WATER, GRAY, BROWN, GRAY, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN, PRIORITY_GREEN, PRIORITY_GREEN
	tilepal 1, WATER, WATER, BROWN, BROWN, BROWN, BROWN, GRAY, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN, PRIORITY_GREEN, PRIORITY_GREEN
	tilepal 1, TEXT, TEXT, TEXT, BROWN, BROWN, BROWN, BROWN, BROWN
