	tilepal 0, GRAY, GRAY, RED, WATER, WATER, WATER, WATER, RED
	tilepal 0, RED, GRAY, WATER, WATER, WATER, WATER, GRAY, GRAY
	tilepal 0, GRAY, RED, RED, WATER, WATER, WATER, WATER, RED
	tilepal 0, RED, GRAY, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 0, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GREEN, GREEN
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN
	tilepal 0, WATER, WATER, WATER, BROWN, BROWN, BROWN, BROWN, WATER
	tilepal 0, WATER, WATER, WATER, WATER, WATER, WATER, GRAY, GRAY
	tilepal 0, WATER, WATER, WATER, BROWN, BROWN, BROWN, BROWN, WATER
	tilepal 0, WATER, WATER, WATER, WATER, GRAY, GRAY, GRAY, GRAY

rept 32
	db $ff
endr

	tilepal 1, BROWN, BROWN, GRAY, GRAY, GRAY, WATER, GRAY, WATER
	tilepal 1, WATER, WATER, WATER, GRAY, GRAY, WATER, GRAY, WATER
	tilepal 1, BROWN, BROWN, GRAY, WATER, WATER, GRAY, GRAY, WATER
	tilepal 1, WATER, WATER, GRAY, GRAY, GRAY, GRAY, WATER, WATER
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, WATER, WATER, WATER, GRAY, GRAY, GRAY, GREEN, GREEN
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN
	tilepal 1, GRAY, GRAY