Icons: ; used only for BANK(Icons)

NullIcon:
PoliwagIcon:      INCBIN "gfx/icons/poliwag.2bpp"
JigglypuffIcon:   INCBIN "gfx/icons/jigglypuff.2bpp"
DiglettIcon:      INCBIN "gfx/icons/diglett.2bpp"
PikachuIcon:      INCBIN "gfx/icons/pikachu.2bpp"
StaryuIcon:       INCBIN "gfx/icons/staryu.2bpp"
FishIcon:         INCBIN "gfx/icons/fish.2bpp"
BirdIcon:         INCBIN "gfx/icons/bird.2bpp"
MonsterIcon:      INCBIN "gfx/icons/monster.2bpp"
ClefairyIcon:     INCBIN "gfx/icons/clefairy.2bpp"
OddishIcon:       INCBIN "gfx/icons/oddish.2bpp"
BugIcon:          INCBIN "gfx/icons/bug.2bpp"
GhostIcon:        INCBIN "gfx/icons/ghost.2bpp"
LaprasIcon:       INCBIN "gfx/icons/lapras.2bpp"
HumanshapeIcon:   INCBIN "gfx/icons/humanshape.2bpp"
FoxIcon:          INCBIN "gfx/icons/fox.2bpp"
EquineIcon:       INCBIN "gfx/icons/equine.2bpp"
ShellIcon:        INCBIN "gfx/icons/shell.2bpp"
BlobIcon:         INCBIN "gfx/icons/blob.2bpp"
SerpentIcon:      INCBIN "gfx/icons/serpent.2bpp"
VoltorbIcon:      INCBIN "gfx/icons/voltorb.2bpp"
SquirtleIcon:     INCBIN "gfx/icons/squirtle.2bpp"
BulbasaurIcon:    INCBIN "gfx/icons/bulbasaur.2bpp"
CharmanderIcon:   INCBIN "gfx/icons/charmander.2bpp"
CaterpillarIcon:  INCBIN "gfx/icons/caterpillar.2bpp"
UnownIcon:        INCBIN "gfx/icons/unown.2bpp"
GeodudeIcon:      INCBIN "gfx/icons/geodude.2bpp"
FighterIcon:      INCBIN "gfx/icons/fighter.2bpp"
EggIcon:          INCBIN "gfx/icons/egg.2bpp"
JellyfishIcon:    INCBIN "gfx/icons/jellyfish.2bpp"
MothIcon:         INCBIN "gfx/icons/moth.2bpp"
BatIcon:          INCBIN "gfx/icons/bat.2bpp"
SnorlaxIcon:      INCBIN "gfx/icons/snorlax.2bpp"
HoOhIcon:         INCBIN "gfx/icons/ho_oh.2bpp"
LugiaIcon:        INCBIN "gfx/icons/lugia.2bpp"
GyaradosIcon:     INCBIN "gfx/icons/gyarados.2bpp"
SlowpokeIcon:     INCBIN "gfx/icons/slowpoke.2bpp"
SudowoodoIcon:    INCBIN "gfx/icons/sudowoodo.2bpp"
BigmonIcon:       INCBIN "gfx/icons/bigmon.2bpp"
BalloonsIcon:	  INCBIN "gfx/icons/balloons.2bpp"
BalloonsOWChrisIcon: INCBIN "gfx/icons/balloonsOWChris.2bpp"
BalloonsOWKrisIcon: INCBIN "gfx/icons/balloonsOWKris.2bpp"

TypeIcons:
	
GhostTypeIcon:		INCBIN "gfx/types/ghost.2bpp"
DarkTypeIcon:		INCBIN "gfx/types/dark.2bpp"
NormalTypeIcon:		INCBIN "gfx/types/normal.2bpp"
GroundTypeIcon:		INCBIN "gfx/types/ground.2bpp"
FireTypeIcon:		INCBIN "gfx/types/fire.2bpp"
PsychicTypeIcon:	INCBIN "gfx/types/psychic.2bpp"
FightingTypeIcon:	INCBIN "gfx/types/fighting.2bpp"
FlyingTypeIcon:		INCBIN "gfx/types/flying.2bpp"
PoisonTypeIcon:		INCBIN "gfx/types/poison.2bpp"
RockTypeIcon:		INCBIN "gfx/types/rock.2bpp"
GrassTypeIcon:		INCBIN "gfx/types/grass.2bpp"
BugTypeIcon:		INCBIN "gfx/types/bug.2bpp"
SteelTypeIcon:		INCBIN "gfx/types/steel.2bpp"
DragonTypeIcon:		INCBIN "gfx/types/dragon.2bpp"
WaterTypeIcon:		INCBIN "gfx/types/water.2bpp"
ElectricTypeIcon:	INCBIN "gfx/types/electric.2bpp"
IceTypeIcon:		INCBIN "gfx/types/ice.2bpp"

TypeIconsPals:

GhostTypeIconPal:		INCLUDE "gfx/types/ghost.pal"
DarkTypeIconPal:		INCLUDE "gfx/types/dark.pal"
NormalTypeIconPal:		INCLUDE "gfx/types/normal.pal"
GroundTypeIconPal:		INCLUDE "gfx/types/ground.pal"
FireTypeIconPal:		INCLUDE "gfx/types/fire.pal"
PsychicTypeIconPal:		INCLUDE "gfx/types/psychic.pal"
FightingTypeIconPal:	INCLUDE "gfx/types/fighting.pal"
FlyingTypeIconPal:		INCLUDE "gfx/types/flying.pal"
PoisonTypeIconPal:		INCLUDE "gfx/types/poison.pal"
RockTypeIconPal:		INCLUDE "gfx/types/rock.pal"
GrassTypeIconPal:		INCLUDE "gfx/types/grass.pal"
BugTypeIconPal:			INCLUDE "gfx/types/bug.pal"
SteelTypeIconPal:		INCLUDE "gfx/types/steel.pal"
DragonTypeIconPal:		INCLUDE "gfx/types/dragon.pal"
WaterTypeIconPal:		INCLUDE "gfx/types/water.pal"
ElectricTypeIconPal:	INCLUDE "gfx/types/electric.pal"
IceTypeIconPal:			INCLUDE "gfx/types/ice.pal"
